name: website

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: '14'
         cache: 'npm'
     - run: npm run dist
     - name: GitHub Pages
       if: success()
       uses: crazy-max/ghaction-github-pages@v2.5.0
       with:
         keep_history: true
         allow_empty_commit: false
         target_branch: gh-pages
         build_dir: script
         dry_run: false
         verbose: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
