name: pages-export-script

on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  pages-export-script:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: '16.13.1'
         cache: 'npm'
     - run: npm i
     - run: npm run export
     - name: GitHub Pages
       if: success()
       uses: crazy-max/ghaction-github-pages@v2.5.0
       with:
         keep_history: true
         allow_empty_commit: false
         target_branch: gh-pages
         build_dir: dist
         dry_run: false
         verbose: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
